version: "3"
services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - .:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    # MySQL公式が用意しているDockerイメージ 8.0.30
    # https://gihyo.jp/dev/serial/01/mysql-road-construction-news/0167
    image: mysql/mysql-server:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  # http://localhost:4040/
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=db
  #     - PMA_USER=root
  #     - PMA_PASSWORD=root
  #   # dbのサービス名
  #   links:
  #     - db
  #   ports:
  #     - 4040:80
  #   volumes:
  #     - ./phpmyadmin/sessions:/sessions

# version: "3"
# services:
#   app:
#     container_name: app
#     build: ./docker/php
#     volumes:
#       - .:/var/www
#   nginx:
#     image: nginx
#     container_name: nginx
#     ports:
#       - 8000:80
#     volumes:
#       - .:/var/www
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     working_dir: /var/www
#     depends_on:
#       - app
#   db:
#     # MySQL公式が用意しているDockerイメージ 8.0.30
#     # https://gihyo.jp/dev/serial/01/mysql-road-construction-news/0167
#     image: mysql/mysql-server:latest
#     container_name: db
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: database
#       MYSQL_USER: db-user
#       MYSQL_PASSWORD: db-pass
#       TZ: "Asia/Tokyo"
#     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#     volumes:
#       - ./docker/db/data:/var/lib/mysql
#       - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
#       - ./docker/db/sql:/docker-entrypoint-initdb.d
#     ports:
#       - 3306:3306

#   # http://localhost:4040/
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       - PMA_ARBITRARY=1
#       - PMA_HOST=db
#       - PMA_USER=root
#       - PMA_PASSWORD=root
#     # dbのサービス名
#     links:
#       - db
#     ports:
#       - 4040:80
#     volumes:
#       - ./phpmyadmin/sessions:/sessions